package me.dzhmud.euler;

import me.dzhmud.euler.util.PositionSequence;

/**
 * Triangular, pentagonal, and hexagonal
 *

 Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
 Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
 Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

 It can be verified that T285 = P165 = H143 = 40755.

 Find the next triangle number that is also pentagonal and hexagonal.

 *
 * @author dzhmud
 */
public class Problem45 implements EulerSolution {

	public static void main(String[] args) {
		long start = System.currentTimeMillis();
		System.out.println(new Problem45().getAnswer());
		System.out.println("Solution take " + (System.currentTimeMillis() - start) / 1000 + " sec");
	}

	@Override
	public String getAnswer() {
		PositionSequence triangle = PositionSequence.get(n -> (long)n*(n+1)/2),
				pentagonal = PositionSequence.get(n -> (long)n*(3*n-1)/2),
				hexagonal = PositionSequence.get(n -> (long)n*(2*n-1));

		//fill sequences to speed up the solution.
		hexagonal.getValue(30000);
		pentagonal.getValue(30000);
		triangle.getValue(60000);
		for (int i = 144; ; i++) {
			long value = hexagonal.getValue(i);
			if (triangle.contains(value) && pentagonal.contains(value)) {
				return "" + value;
			}
		}
	}

}
